# -*- coding: utf-8 -*-
"""Convert C to F and km to mi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mP-veF9I4FSYs13Uhv9wezY4xkpSFUh8
"""

input_value = input("Enter the C value you want to convert: ")
C = float(input_value)
F = (C * 1.8) + 32
print(F, "F")

input_value = input("Enter the km value you want to convert: ")
km = float(input_value)
mi = km * 0.62137
print(mi, "mi")