# -*- coding: utf-8 -*-
"""most_frequently_nums

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJPTv-tjlqdI20XD4W-HhkwNciS3a96b
"""

listA = [10, 20, 10, 30, 20, 40, 20, 20, 50, 20, 30, 20]
print("Given List:\n",listA)
res = max(set(listA), key = listA.count)
text = "the most frequent number is {} and it was {} times repeated".format(res, listA.count(res))
print(text)